#!/bin/bash

export HOMEDIR=$(dirname "$0")
export WORKDIR=$(pwd)

if [ $1 != web ]; then
	singularity build --fakeroot $HOMEDIR/spikeScreenContainer.sif $HOMEDIR/Singularity
else
	singularity pull shub://fifthguy/spikeScreenContainer
	mv spikeScreenContainer*.sif $HOMEDIR/spikeScreenContainer.sif
fi
