#!/bin/bash

export HOMEDIR=$(dirname "$0")
export WORKDIR=$(pwd)
export RUNDIR=$WORKDIR/runs
export RESULTSDIR=$WORKDIR/results
export LOGDIR=$WORKDIR/logs

export INSTANCE_NAME=$(date +"%Y%m%d%H%M%S")-$2
export DATA_ORIGIN=$3


echo $HOMEDIR;

if [ ! -f "$HOMEDIR/spikeScreenContainer.sif" ]; then
	$HOMEDIR/buildContainer local
fi

if [  ! -d "$RUNDIR" ]; then
	mkdir $RUNDIR
fi

if [ ! -d "$RESULTSDIR" ]; then
	mkdir $RESULTSDIR
fi

if [ ! -d "$LOGDIR" ]; then
	mkdir $LOGDIR
fi

#########################################################################

cp -r $HOMEDIR/poolsPipeline $RUNDIR/${INSTANCE_NAME}

cp $DATA_ORIGIN/* $RUNDIR/$INSTANCE_NAME/Fastq/

cd $RUNDIR/${INSTANCE_NAME}

./procedure_2LIB_consensus 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.log

cp -r results $RESULTSDIR/${INSTANCE_NAME}

cd $WORKDIR

rm -r $RUNDIR/$INSTANCE_NAME


