#!/bin/bash

export HOMEDIR=$(dirname "$0")
export WORKDIR=$(pwd)
export RUNDIR=$WORKDIR/runs
export RESULTSDIR=$WORKDIR/results
export LOGDIR=$WORKDIR/logs

export INSTANCE_NAME=$(date +"%Y%m%d%H%M%S")-$1
export DATA_ORIGIN=$2

########################################################################

# echo $HOMEDIR;

if [  ! -d "$RUNDIR" ]; then
	mkdir $RUNDIR
fi

if [ ! -d "$RESULTSDIR" ]; then
	mkdir $RESULTSDIR
fi

if [ ! -d "$LOGDIR" ]; then
	mkdir $LOGDIR
fi

#########################################################################

cp -r $HOMEDIR/poolsPipeline $RUNDIR/${INSTANCE_NAME}

mkdir $RUNDIR/$INSTANCE_NAME/Fastq
cp $DATA_ORIGIN/* $RUNDIR/$INSTANCE_NAME/Fastq/

cd $RUNDIR/${INSTANCE_NAME}

./procedure_2LIB_consensus 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.log

cp -r results $RESULTSDIR/${INSTANCE_NAME}

cd $WORKDIR

rm -r $RUNDIR/$INSTANCE_NAME

##########################################################################
