#!/bin/bash

export HOMEDIR=$(dirname "$0")
export WORKDIR=$(pwd)
export RUNDIR=$WORKDIR/runs
export RESULTSDIR=$WORKDIR/results
export LOGDIR=$WORKDIR/logs

# export INSTANCE_NAME=$(date +"%Y%m%d%H%M%S")-${2}-${1}
export INSTANCE_NAME=${1}-${2}
export DATA_ORIGIN=$3

########################################################################

# echo $HOMEDIR;

if [  ! -d "$RUNDIR" ]; then
	mkdir $RUNDIR
fi

if [ ! -d "$RESULTSDIR" ]; then
	mkdir $RESULTSDIR
fi

if [ ! -d "$LOGDIR" ]; then
	mkdir $LOGDIR
fi

#########################################################################

if [ -d "$RUNDIR/$INSTANCE_NAME" ]; then
    rm -r $RUNDIR/$INSTANCE_NAME
fi

if [ -d "$RESULTSDIR/$INSTANCE_NAME" ]; then
    rm -r $RESULTSDIR/$INSTANCE_NAME
fi

#########################################################################

cp -r $HOMEDIR/poolsPipeline $RUNDIR/${INSTANCE_NAME}

mkdir $RUNDIR/$INSTANCE_NAME/Fastq
cp $DATA_ORIGIN/* $RUNDIR/$INSTANCE_NAME/Fastq/

cd $RUNDIR/${INSTANCE_NAME}

if [ $2 == pools ]; then
	./procedure_2LIB_Spools 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.log
elif [ $2 == pools_single ]; then
	./procedure_1LIB_Spools 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.log
elif [ $2 == assemblies ]; then
	./procedure_2LIB_assemblies 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.logel
if [ $2 == assemblies_single ]; then
	./procedure_1LIB_assemblies 1>$LOGDIR/${INSTANCE_NAME}.stdout.log 2>$LOGDIR/${INSTANCE_NAME}.stderr.log
else
	echo "Please specify analysis type"
fi

cp -r results $RESULTSDIR/${INSTANCE_NAME}

cd $WORKDIR

# rm -r $RUNDIR/$INSTANCE_NAME

##########################################################################
